apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Values.chart_name }}
spec:
  secretName: {{ .Values.chart_name }}-tls
  issuerRef:
    name: letsencrypt-production-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.fqdn }}
  acme:
    config:
    - http01: {}
      domains:
      - {{ .Values.fqdn }}
