kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.chart_name }}
data:
  keycloak.yml: |-
    discovery-url: {{ .Values.discovery_url }}
    client-id: broker
    client-secret: {{ .Values.client_secret }}
    redirection-url: https://{{ .Values.fqdn }}
    revocation-url: {{ .Values.logout_url }}
    listen: 0.0.0.0:8000
    upstream-url: http://127.0.0.1:8081
    scopes:
    - vpn-user
    resources:
    - uri: /*
      roles:
      - vpn-user
    add-claims:
    - name
    - given_name
    - family_name
    match-claims:
      aud: broker

  portal.yml: |-
    listen: :8081
    verbose: true
    banner: Secureweb VPN Portal
    logout-url: {{ .Values.logout_url }}
    help-url: {{ .Values.help_url }}
    host: {{ .Values.vpn_remote }}
    port: {{ .Values.vpn_port }}
    fullname-header: X-Auth-Fullname
    username-header: X-Auth-Username
    roles-header: X-Auth-Roles
    ca-certificate-file: /home/app/secrets/ca.pem
    ca-private-file: /home/app/secrets/ca-key.pem
    configdir-enabled: true
    configdir-path: /home/app/profiles
    profiles:
    - name: livedata
      description: Live Data
      max-session: 2h
      roles:
        - vpn-livedata
      routes:
        - route: 192.168.1.0
          netmask: 255.255.255.0
      rules:
        - dest: 192.168.1.0/24
          port: 53
          protocol: tcp
          action: ACCEPT
    - name: notlivedata
      description: Not Live Data
      max-session: 8h
      roles:
        - vpn-notlivedata
      routes:
        - route: 172.16.0.0
          netmask: 255.255.255.0
      rules:
        - dest: 172.16.0.0/16
          port: 53
          protocol: udp
          action: ACCEPT

    template: |
      #
      # Expiration of Certificate: {{ "{{ .Session.ExpiresOn }}" }}
      # Session Duration: {{ "{{ .Session.Duration }}" }}
      # VPN Profile for: {{ "{{ .Session.Profile }}" }}
      #

      client
      dev tun
      proto tcp
      remote {{ "{{ .Session.Hostname }} {{ .Session.Port }}" }}
      resolv-retry infinite
      remote-cert-tls server
      nobind
      persist-key
      persist-tun
      ca [inline]
      cert [inline]
      key [inline]
      verb 1
      keepalive 10 900
      inactive 3600
      cipher AES-256-CBC

      <ca>
      {{ "{{ .Session.IssuingCA }}" }}</ca>

      <cert>
      {{ "{{ .Session.Certificate }}" }}</cert>

      <key>
      {{ "{{ .Session.PrivateKey }}" }}</key>

  openvpn.conf: |-
    local 0.0.0.0
    port 1194
    proto tcp
    dev tun
    ca /etc/secrets/ca.pem
    cert /etc/secrets/vpn.pem
    key /etc/secrets/vpn-key.pem
    dh /etc/secrets/dh.pem
    client-config-dir /etc/openvpn/profiles
    ccd-exclusive
    remote-random
    server 10.100.10.0 255.255.255.0
    management 127.0.0.1 1234
    duplicate-cn
    tls-version-min 1.2
    tls-cipher TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256:TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256:TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384:TLS-DHE-RSA-WITH-AES-256-CBC-SHA256
    cipher AES-256-CBC
    keepalive 10 120
    inactive 3600
    script-security 2
    persist-key
    persist-tun
    status /var/log/openvpn-status.log
