apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.chart_name }}
type: Opaque
data:
  client-secret: {{ b64enc .Values.client_secret }}
  dh.pem: {{ .Values.dh_pem  }}
  ca.pem: {{ .Values.ca_pem }}
  ca-key.pem: {{ .Values.ca_key }}
  vpn.pem: {{ .Values.vpn_pem }}
  vpn-key.pem: {{ .Values.vpn_key }}
