apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chart_name }}-portal
spec:
  ports:
    - name: vpn
      port: 8000
      targetPort: 8000
  type: ClusterIP
  selector:
    app: {{ .Values.chart_name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chart_name }}
spec:
  ports:
    - name: vpn
      port: 1194
      targetPort: 1194
      nodePort: 31194
  type: NodePort
  selector:
    app: {{ .Values.chart_name }}
